language: node_js
node_js:
  - 0.8
  - 0.10
before_install:
  - npm install -g dredd
script: ./scripts/test
services:
  - mongodb
notifications:
  email:
    recipients:
      - adam@apiary.io
    on_success: change
    on_failure: always
before_script:
  - mongo mydb_test --eval 'db.addUser("test", "test");'
